services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
    
    networks:
      - library
  
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.local

    environment:
      GITLAB_HOST: ${HOST}

      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${HOST}/gitlab'

        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        gitlab_rails['gitlab_shell_ssh_port'] = 2222

    ports:
      - "2222:22"

    volumes:
      - /home/ansible/gitlab-volumes/config:/etc/gitlab
      - /home/ansible/gitlab-volumes/logs:/var/log/gitlab
      - /home/ansible/gitlab-volumes/data:/var/opt/gitlab

    shm_size: "256m"

    networks:
      - library

networks:
  library:
    external: true
    name: library